language: cpp

notifications:
  email:
    recipients:
      - akohlmey@gmail.com
    on_successs: change
    on_failure: always

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpi-default-bin mpi-default-dev libfftw3-dev libjpeg-dev libpng12-dev python-dev

env:
  - MACH=serial LMPFLAGS="-sf off" LMP_INC="-DLAMMPS_GZIP -DLAMMPS_PNG -DLAMMPS_JPEG" JPG_LIB="-ljpeg -lpng -lz"
  - MACH=mpi MPICMD="mpirun -np 4" LMPFLAGS="-pk omp 2 -sf omp" LMP_INC="-DFFT_FFTW3 -DLAMMPS_GZIP -DLAMMPS_PNG -DLAMMPS_JPEG -DLAMMPS_SMALLBIG" JPG_LIB="-lfftw3 -ljpeg -lpng -lz"
  - MACH=mpi MPICMD="mpirun -np 4" LMPFLAGS="-pk omp 2 -sf omp" LMP_INC="-DFFT_FFTW3 -DLAMMPS_GZIP -DLAMMPS_PNG -DLAMMPS_JPEG -DLAMMPS_SMALLSMALL" JPG_LIB="-lfftw3 -ljpeg -lpng -lz"
  - MACH=mpi MPICMD="mpirun -np 4" LMPFLAGS="-pk omp 2 -sf omp" LMP_INC="-DFFT_FFTW3 -DLAMMPS_GZIP -DLAMMPS_PNG -DLAMMPS_JPEG -DLAMMPS_BIGBIG" JPG_LIB="-lfftw3 -ljpeg -lpng -lz"

install:
  - export OMPI_CC=$CC
  - export OMPI_CXX=$CXX
  - test "$MACH" = "mpi" && export COMP="mpicxx -fopenmp" || export COMP="$CXX"

script:
  - make -C src clean-all
  - make -C src yes-all
  - make -C src no-lib
  - make -C src yes-user-smd yes-user-molfile yes-compress yes-python
  - make -C lib/colvars -f Makefile.g++ CXX="${COMP}"
  - make -C lib/poems -f Makefile.g++ CXX="${COMP}"
  - make -C lib/voronoi -f Makefile.g++ CXX="${COMP}"
  - make -C src yes-poems yes-voronoi yes-user-colvars 
  - test "$MACH" = mpi && make -C src yes-mpiio yes-user-lb || true
  - make -C src test-${MACH} MPICMD="${MPICMD}" CC="${COMP}" LINK="${COMP}" LMP_INC="${LMP_INC}" JPG_LIB="${JPG_LIB}" TAG="${TAG}-$CC" LMPFLAGS="${LMPFLAGS}"
